[workspace]
members = [
    "crates/encore",
    "crates/pixie",
    "crates/minipak",
    "crates/stage1",
    "crates/stage2",
]

[profile.dev]
panic = "abort"

[profile.release]
debug = true
lto = "thin"
panic = "abort"